### ISSUE TITLE
sh: dvipng: command not found

### ISSUE THREAD

**Issue by ameirshaa** [CERNatschool/fast-cluster-analysis#2]
Hi @twhyntie, 

what does dvipng do? the terminal is unable to find that command and process a few files.

**Comment by twhyntie** [comment]
@ameirshaa [It converts DVI files to PNG files](https://www.google.co.uk/?gws_rd=ssl#safe=active&q=dvipng) - it's used by `matplotlib` to do some converting between graphics formats.

It looks like it's not installed on the CernVM by default, so you'll have to comment out lines 31 and 32 of [plotting/histograms.py](https://github.com/CERNatschool/fast-cluster-analysis/blob/master/plotting/histograms.py) for now. (In fact this did used to be commented out by default, but I must have committed a version with them uncommented.)

**Comment by ameirshaa** [comment]
@twhyntie I should have been more specific. The problem lies in compare-plots.py

**Comment by twhyntie** [comment]
@ameirshaa Yes, but this calls the code I reference :smile:

**Comment by ameirshaa** [comment]
Alright! It works just fine now! Thank you @twhyntie! :)

**Comment by twhyntie** [comment]
You're welcome - but the offending lines should be commented out - I'll close the issue when I get time to make the commit.

Thanks for pointing it out and I'm glad it's working now - enjoy the plots! :smile:
