### ISSUE TITLE
Calibrate the energy value to keV

### ISSUE THREAD

**Issue by NickKok** [CERNatschool/fast-cluster-analysis#3]
Hello @twhyntie,

I making an application for timepix2 and i am using some of your code to make the clustering of each frame. Because it is more clear to see the energy at KeV (at least for me)

I have done this function:
`    
def calibrate(total):

        a=1.54505
        b=50.6605 - (1.54505*1.19535) - total
        c = -141.279 - (1.19535*50.6605)  + (total*1.19535)
        sol1 = -b + math.sqrt(b*b - 4*a*c)
        sol1 /= 2*a
        sol2 = -b - math.sqrt(b*b - 4*a*c)
        sol2 /= 2*a
        sol=0
        #cout << "______________________________________" << endl;
        #cout << "sol1 : " << sol1 << " | sol2 : " << sol2 << endl;
        if (sol1 > 0 and sol2 > 0):
            sol=max(sol1,sol2)
        elif(sol2 <= 0 and sol1 > 0):
            sol = sol1
        else:
            sol = sol2      
        return sol
`

To make calibrate the energy to Kev. 
I just mention it if anyone else need it.

**Comment by twhyntie** [comment]
Great, thanks! Just bear in mind that those values you have used will only be accurate for **one pixel** - all of the 65,536 pixels in a Timepix detector have their own calibration constants which are obtained from the calibration procedure described [here](http://dx.doi.org/10.1016/j.nima.2010.06.183). So the code above should be fine for illustrative purposes, but proceed with caution when using for actual scientific results :wink:
